params:
  -
      name: t
      keys:
        # param
        discipline: 0
        parameterCategory: 0
        parameterNumber: 0

        # level
        typeOfLevel: isobaricInPa

  -
      name: h
      keys:
        # param
        discipline: 0
        parameterCategory: 3
        parameterNumber: 5

        # level
        typeOfLevel: isobaricInPa