# this is a sample config file for GradsToGrib.

#common:
#  keys:
#    dataDate: 20180212  # YYYYMMDD
#    dataTime: 0         # Hour
#    indicatorOfUnitOfTimeRange: 1
#    forecastTime: 0     # Start Hour

grads_ctl:
  props:
    start_time: 2018021200
    forecast_hour: 000
    data_endian: big_endian

params:
  -
    name: t
    levels: [1000, 975]
    keys:
      # param
      discipline: 0
      parameterCategory: 0
      parameterNumber: 0

      # level
      typeOfLevel: isobaricInPa
